package AdResponseUtils;

import bmp.HarParser;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import global.Global_for_JSON;
import net.lightbody.bmp.core.har.Har;

import java.io.IOException;

import static bmp.HarParser.getEntries;

/**
 * Implements methods for parsing OM events generated by omsdk script in server ads.
 */
public class AdResponseParserURL implements AdResponseParser {

    // ----------------------------------------------------------------------
    // Private constants
    // ----------------------------------------------------------------------

    private static class JSON_PATH {
        public static String EVENT = "$.request.queryString";
        public static final String AD_ID = "ads[adunits][0][chain][0][ad_id]";
        public static final String CREATIVE_ID = "auid";
    }

    public static JsonArray getEntriesWithEventInUrl(Har harLog, String event) {
        JsonArray results = new JsonArray();
        for (JsonElement entry : getEntries(harLog)) {
            if (entry.getAsJsonObject().getAsJsonObject("request").get("url").getAsString().contains(event)) {
                results.add(entry);
            }
        }
        return results;
    }

    public static String getResponseTextName(Har harLog, String event){
        return getEntriesWithEventInUrl(harLog, event).get(0).getAsJsonObject().getAsJsonObject("response")
                .getAsJsonObject("content")
                .get("text")
                .getAsString();
    }

    public String getDisplayAdIdValue(Har har, String event) throws IOException {
        return Global_for_JSON.getJsonValue(getResponseTextName(har, event), JSON_PATH.AD_ID);
    }


    public String getVideoAdIdValue(Har har, String event) throws NoSuchFieldException {
        return HarParser.getValueOfPostDataArg(har, event, JSON_PATH.CREATIVE_ID);
    }

}
