package appium.common;

import org.json.JSONObject;
import utils.FileUtils;
import utils.RequestTemplate;

import java.util.HashMap;

public class InAppTemplatesInit {
    public static JSONObject getAuctionRequestTemplate(String prebidAd, String platformName, RequestTemplate requestTemplate) {
        String filePath = getFilePathAuctionRequest(prebidAd, platformName, requestTemplate);
        System.out.println("TEMPLATE PATH IS ==> " + filePath + "\n");
        final String testJSON = FileUtils.getJsonStringFromResourceFile(filePath);
        return new JSONObject(testJSON);
    }

    public static JSONObject getAuctionRequestTemplate(String prebidAd, String platformName) {
        String filePath = getFilePath(requestTemplates.get(prebidAd), platformName);
        System.out.println("TEMPLATE PATH IS ==> " + filePath + "\n");
        final String testJSON = FileUtils.getJsonStringFromResourceFile(filePath);
        return new JSONObject(testJSON);
    }

    public static JSONObject getAuctionResponseTemplate(String prebidAd, String platformName) {
        final String filePath = getFilePath(responseTemplates.get(prebidAd), platformName);
        System.out.println("RESPONSE TEMPLATE PATH IS ==> " + filePath + "\n");
        final String testJSON = FileUtils.getJsonStringFromResourceFile(filePath);
        return new JSONObject(testJSON);
    }

    public static void setOriginalApiMultiformatResponseTemplate(String multiformatAd, String config) {
        switch (multiformatAd) {
            case InAppAdNames.BANNER_300x250_GAM_ORIGINAL_MULTIFORMAT:
               responseTemplates.put(InAppAdNames.BANNER_300x250_GAM_ORIGINAL_MULTIFORMAT, config.contains("video") ? InAppTemplates.RESPONSE_TEMPLATE_VIDEO_OUTSTREAM_MF : InAppTemplates.RESPONSE_TEMPLATE_BANNER_MF);
               break;
            case InAppAdNames.INTERSTITIAL_320x480_MULTIFORMAT_ORIGINAL:
                responseTemplates.put(InAppAdNames.INTERSTITIAL_320x480_MULTIFORMAT_ORIGINAL, config.contains("video") ? InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL_MF : InAppTemplates.RESPONSE_TEMPLATE_DISPLAY_INTERSTITIAL_MF);
                break;
        }
    }

    private static String getFilePathAuctionRequest(String prebidAd, String platformName, RequestTemplate requestTemplate) {
        switch (requestTemplate) {
            case REQUEST_SIMULATOR:
                return getFilePath(requestTemplates.get(prebidAd), platformName);
            case REQUEST_CACHE:
                return getFilePath(requestWithCacheTemplates.get(prebidAd), platformName);
            case REQUEST_ADDITIONAL_PARAMS:
                return getFilePath(requestWithAdditionalParamsTemplates.get(prebidAd), platformName);
            case REQUEST_REAL_DEVICE:
                return getFilePath(realDeviceRequestTemplates.get(prebidAd), platformName);
            case REQUEST_FIRST_PARTY:
                return getFilePath(requestWithFirstPartyData.get(prebidAd), platformName);
            default:
                throw new IllegalStateException("Unexpected value: " + requestTemplate);
        }
    }

    private static String getFilePath(String path, String platformName) {
        return String.format(path, platformName);
    }

    private final static HashMap<String, String> requestTemplates = new HashMap<>() {{
        put(InAppAdNames.BANNER_320x50_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_IN_APP_SCROLLABLE, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_IN_APP_VAST, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_IN_APP_DEEPLINK, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_NO_BID_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);

        put(InAppAdNames.BANNER_320x50_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_NO_BID_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_ADMOB_RANDOM, InAppTemplates.TEMPLATE_BANNER_320x50);

        put(InAppAdNames.BANNER_320x50_MAX, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_NO_BID_MAX, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_MAX_RANDOM, InAppTemplates.TEMPLATE_BANNER_320x50);

        put(InAppAdNames.BANNER_320x50_GAM, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_GAM_ORIGINAL, InAppTemplates.TEMPLATE_BANNER_320x50_ORIGINAL);
        put(InAppAdNames.BANNER_320x50_GAM_ORIGINAL_NO_SKADN, InAppTemplates.TEMPLATE_BANNER_320x50_ORIGINAL);
        put(InAppAdNames.BANNER_320x50_GAM_AD, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_GAM_RANDOM, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_GAM_VANILLA, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.BANNER_320x50_NO_BID_GAM_AD, InAppTemplates.TEMPLATE_BANNER_320x50);

        put(InAppAdNames.BANNER_300x250_IN_APP, InAppTemplates.TEMPLATE_BANNER_300x250);
        put(InAppAdNames.BANNER_300x250_GAM, InAppTemplates.TEMPLATE_BANNER_300x250);
        put(InAppAdNames.BANNER_300x250_GAM_ORIGINAL, InAppTemplates.TEMPLATE_BANNER_300x250_ORIGINAL);
        put(InAppAdNames.BANNER_300x250_GAM_ORIGINAL_MULTIFORMAT, InAppTemplates.TEMPLATE_BANNER_300x250_ORIGINAL_MF);
        put(InAppAdNames.BANNER_300x250_ADMOB, InAppTemplates.TEMPLATE_BANNER_300x250);
        put(InAppAdNames.BANNER_300x250_MAX, InAppTemplates.TEMPLATE_BANNER_300x250);
        put(InAppAdNames.BANNER_ADAPTIVE_ADMOB, InAppTemplates.TEMPLATE_BANNER_MULTISIZE);
        put(InAppAdNames.BANNER_ADAPTIVE_MAX, InAppTemplates.TEMPLATE_BANNER_MULTISIZE);

        put(InAppAdNames.BANNER_728x90_IN_APP, InAppTemplates.TEMPLATE_BANNER_728x90);
        put(InAppAdNames.BANNER_728x90_GAM, InAppTemplates.TEMPLATE_BANNER_728x90);
        put(InAppAdNames.BANNER_728x90_GAM_ORIGINAL, InAppTemplates.TEMPLATE_BANNER_728x90_ORIGINAL);

        put(InAppAdNames.BANNER_MULTISIZE_IN_APP, InAppTemplates.TEMPLATE_BANNER_MULTISIZE);
        put(InAppAdNames.BANNER_MULTISIZE_GAM, InAppTemplates.TEMPLATE_BANNER_MULTISIZE);
        put(InAppAdNames.BANNER_MULTISIZE_GAM_ORIGINAL, InAppTemplates.TEMPLATE_BANNER_MULTISIZE_ORIGINAL);

        put(InAppAdNames.BANNER_SKADNETWORK, InAppTemplates.TEMPLATE_BANNER_320x50_SKADN);
        put(InAppAdNames.LIVE_RAMP_ATS, InAppTemplates.TEMPLATE_BANNER_320x50_LIVERAMP);
        put(InAppAdNames.GPP, InAppTemplates.TEMPLATE_BANNER_320x50_GPP);
        put(InAppAdNames.ATTS_1, InAppTemplates.TEMPLATE_BANNER_320x50_ATTS_1);
        put(InAppAdNames.ATTS_2, InAppTemplates.TEMPLATE_BANNER_320x50_ATTS_2);
        put(InAppAdNames.ATTS_3, InAppTemplates.TEMPLATE_BANNER_320x50_ATTS_3);
        put(InAppAdNames.CUSTOM_USPRIVACY_CCPA_TRUE, InAppTemplates.TEMPLATE_BANNER_320x50_CCPA_TRUE);
        put(InAppAdNames.CUSTOM_OPENRTB, InAppTemplates.TEMPLATE_BANNER_320x50_CUSTOM_ORTB);
        put(InAppAdNames.CUSTOM_USPRIVACY_CCPA_FALSE, InAppTemplates.TEMPLATE_BANNER_320x50_CCPA_FALSE);
        put(InAppAdNames.CUSTOM_TCF_GDPR0_NO_CONSENT, InAppTemplates.TEMPLATE_BANNER_320x50_GDPR0_CONS_NULL);
        put(InAppAdNames.CUSTOM_TCF_GDPR1_CONSENT, InAppTemplates.TEMPLATE_BANNER_320x50_GDPR1_CONS_TRUE);
        put(InAppAdNames.CUSTOM_TCF_NO_GDPR_NO_CONSENT, InAppTemplates.TEMPLATE_BANNER_320x50_CCPA_FALSE);

        put(InAppAdNames.INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_IN_APP_SKADN, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_SKADN);
        put(InAppAdNames.INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_ORIGINAL);
        put(InAppAdNames.INTERSTITIAL_320x480_MULTIFORMAT_ORIGINAL, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_ORIGINAL_MF);
        put(InAppAdNames.INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);

        put(InAppAdNames.INTERSTITIAL_320x480_GAM_RANDOM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_ADMOB_RANDOM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_MAX_RANDOM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);

        put(InAppAdNames.INTERSTITIAL_320x480_NO_BID_GAM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_NO_BID_ADMOB, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);
        put(InAppAdNames.INTERSTITIAL_320x480_NO_BID_MAX, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480);

        put(InAppAdNames.INTERSTITIAL_320x480_MULTISIZE_GAM, InAppTemplates.TEMPLATE_BANNER_MULTISIZE);

        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_IN_APP, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_GAM, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_ADMOB, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_MAX, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP_SKADN, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_SKADN);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ENDCARD, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_ORIGINAL);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_RANDOM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_NO_BID_GAM_AD, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB_RANDOM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_NO_BID_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX_RANDOM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_NO_BID_MAX, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480);

        put(InAppAdNames.VIDEO_REWARDED_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_IN_APP_SKADN, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_SKADN);
        put(InAppAdNames.VIDEO_REWARDED_320x480_IN_APP_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);


        put(InAppAdNames.VIDEO_REWARDED_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_ADMOB_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_NO_BID_ADMOB, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_ADMOB_RANDOM, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);

        put(InAppAdNames.VIDEO_REWARDED_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_MAX_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_NO_BID_MAX, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_MAX_RANDOM, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);

        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_METADATA, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_ORIGINAL, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_ORIGINAL);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_WITH_AD_CONFIGURATION, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_NO_BID_GAM, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_RANDOM, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480);

        put(InAppAdNames.VIDEO_OUTSTREAM_IN_APP, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250);
        put(InAppAdNames.VIDEO_OUTSTREAM_IN_APP_SKADN, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250_SKADN);
        put(InAppAdNames.VIDEO_OUTSTREAM_FEED_IN_APP, InAppTemplates.TEMPLATE_VIDEO_FEED_300x250);
        put(InAppAdNames.VIDEO_OUTSTREAM_ENDCARD, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250);

        put(InAppAdNames.VIDEO_OUTSTREAM_GAM, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250);
        put(InAppAdNames.VIDEO_OUTSTREAM_GAM_ORIGINAL, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250_ORIGINAL);
        put(InAppAdNames.VIDEO_INSTREAM_GAM_ORIGINAL, InAppTemplates.TEMPLATE_VIDEO_INSTREAM_300x250_ORIGINAL);
        put(InAppAdNames.VIDEO_OUTSTREAM_FEED_GAM, InAppTemplates.TEMPLATE_VIDEO_FEED_300x250);
        put(InAppAdNames.VIDEO_OUTSTREAM_NO_BID_GAM_AD, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250);
        put(InAppAdNames.VIDEO_OUTSTREAM_GAM_RANDOM, InAppTemplates.TEMPLATE_VIDEO_OUTSTREAM_300x250);

        put(InAppAdNames.MRAID_EXPAND_1_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.MRAID_EXPAND_2_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.MRAID_RESIZE_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.MRAID_RESIZE_WITH_ERRORS_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.MRAID_VIDEO_INTERSTITIAL_IN_APP, InAppTemplates.TEMPLATE_MRAID_VIDEO_INTERSTITIAL);
        put(InAppAdNames.MRAID_FULLSCREEN_IN_APP, InAppTemplates.TEMPLATE_MRAID_FULLSCREEN);

        put(InAppAdNames.MRAID_VIDEO_INTERSTITIAL_GAM, InAppTemplates.TEMPLATE_MRAID_VIDEO_INTERSTITIAL);
        put(InAppAdNames.MRAID_EXPAND_1_GAM, InAppTemplates.TEMPLATE_BANNER_320x50);
        put(InAppAdNames.MRAID_RESIZE_GAM, InAppTemplates.TEMPLATE_BANNER_320x50);

        //NATIVE CASES

        put(InAppAdNames.NATIVE_AD_ADMOB, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_ADMOB_NO_BIDS, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_ADMOB_GAD_NO_BIDS, InAppTemplates.REQUEST_TEMPLATE_NATIVE);

        put(InAppAdNames.NATIVE_AD_MAX, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_MAX_NO_BIDS, InAppTemplates.REQUEST_TEMPLATE_NATIVE);

        put(InAppAdNames.NATIVE_AD_IN_APP, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_FEED_IN_APP, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_LINKS_IN_APP, InAppTemplates.REQUEST_TEMPLATE_NATIVE);

        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE_GAD, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_ORIGINAL, InAppTemplates.REQUEST_TEMPLATE_NATIVE_ORIGINAL);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED_GAD, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_FEED_GAM, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED_GAD_NO_BIDS, InAppTemplates.REQUEST_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE_GAD_NO_BIDS, InAppTemplates.REQUEST_TEMPLATE_NATIVE);

    }};
    private final static HashMap<String, String> requestWithCacheTemplates = new HashMap<String, String>() {{
        put(InAppAdNames.BANNER_320x50_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50_CACHE);
        put(InAppAdNames.BANNER_320x50_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50_CACHE);
        put(InAppAdNames.BANNER_320x50_MAX, InAppTemplates.TEMPLATE_BANNER_320x50_CACHE);
        put(InAppAdNames.BANNER_320x50_GAM, InAppTemplates.TEMPLATE_BANNER_320x50_CACHE);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_CACHE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_CACHE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_CACHE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_CACHE);
    }};
    private final static HashMap<String, String> requestWithAdditionalParamsTemplates = new HashMap<String, String>() {{
        put(InAppAdNames.BANNER_320x50_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50_ADDITIONAL_PARAMS);
        put(InAppAdNames.BANNER_320x50_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50_ADDITIONAL_PARAMS);
        put(InAppAdNames.BANNER_320x50_MAX, InAppTemplates.TEMPLATE_BANNER_320x50_ADDITIONAL_PARAMS);
        put(InAppAdNames.BANNER_320x50_GAM, InAppTemplates.TEMPLATE_BANNER_320x50_ADDITIONAL_PARAMS);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_ADDITIONAL_PARAMS);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_ADDITIONAL_PARAMS);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_ADDITIONAL_PARAMS);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_ADDITIONAL_PARAMS);
    }};
    private final static HashMap<String, String> requestWithFirstPartyData = new HashMap<>() {{
            put(InAppAdNames.BANNER_320x50_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50_FIRST_PARTY);
            put(InAppAdNames.BANNER_320x50_GAM, InAppTemplates.TEMPLATE_BANNER_320x50_FIRST_PARTY);
            put(InAppAdNames.BANNER_320x50_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50_FIRST_PARTY);
            put(InAppAdNames.BANNER_320x50_GAM_ORIGINAL, InAppTemplates.TEMPLATE_BANNER_320x50_ORIGINAL_FIRST_PARTY);
            put(InAppAdNames.NATIVE_AD_ADMOB, InAppTemplates.REQUEST_TEMPLATE_NATIVE_FIRST_PARTY);
            put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_FIRST_PARTY);
            put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_FIRST_PARTY);
            put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_FIRST_PARTY);
    }};

    private final static HashMap<String, String> realDeviceRequestTemplates = new HashMap<String, String>() {{
        put(InAppAdNames.BANNER_320x50_IN_APP, InAppTemplates.TEMPLATE_BANNER_320x50_REAL_DEVICE);
        put(InAppAdNames.BANNER_320x50_GAM, InAppTemplates.TEMPLATE_BANNER_320x50_REAL_DEVICE);
        put(InAppAdNames.BANNER_320x50_ADMOB, InAppTemplates.TEMPLATE_BANNER_320x50_REAL_DEVICE);
        put(InAppAdNames.BANNER_320x50_MAX, InAppTemplates.TEMPLATE_BANNER_320x50_REAL_DEVICE);

        put(InAppAdNames.INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_INTERSTITIAL_320x480_REAL_DEVICE);

        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_IN_APP, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_MAX, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_GAM, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT_REAL_DEVICE);
        put(InAppAdNames.INTERSTITIAL_MULTI_FORMAT_ADMOB, InAppTemplates.TEMPLATE_INTERSTITIAL_MULTIFORMAT_REAL_DEVICE);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_INTERSTITIAL_320x480_REAL_DEVICE);

        put(InAppAdNames.VIDEO_REWARDED_320x480_IN_APP, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_REWARDED_320x480_ADMOB, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_METADATA, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_REAL_DEVICE);
        put(InAppAdNames.VIDEO_REWARDED_320x480_MAX, InAppTemplates.TEMPLATE_VIDEO_REWARDED_320x480_REAL_DEVICE);

        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE, InAppTemplates.REQUEST_TEMPLATE_NATIVE_REAL_DEVICE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED, InAppTemplates.REQUEST_TEMPLATE_NATIVE_REAL_DEVICE);
        put(InAppAdNames.NATIVE_AD_ADMOB, InAppTemplates.REQUEST_TEMPLATE_NATIVE_REAL_DEVICE);
        put(InAppAdNames.NATIVE_AD_IN_APP, InAppTemplates.REQUEST_TEMPLATE_NATIVE_REAL_DEVICE);
        put(InAppAdNames.NATIVE_AD_MAX, InAppTemplates.REQUEST_TEMPLATE_NATIVE_REAL_DEVICE);

    }};
    private final static HashMap<String, String> responseTemplates = new HashMap<>() {{
        put(InAppAdNames.BANNER_320x50_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_BANNER);
        put(InAppAdNames.BANNER_300x250_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_BANNER);
        put(InAppAdNames.BANNER_728x90_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_BANNER);
        put(InAppAdNames.BANNER_MULTISIZE_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_BANNER);
        put(InAppAdNames.INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_DISPLAY_INTERSTITIAL);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL);
        put(InAppAdNames.VIDEO_OUTSTREAM_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_OUTSTREAM);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED);
        put(InAppAdNames.VIDEO_INSTREAM_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INSTREAM);

        //NATIVE CASES
        put(InAppAdNames.NATIVE_AD_ADMOB, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_ADMOB_NO_BIDS, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_ADMOB_GAD_NO_BIDS, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);


        put(InAppAdNames.BANNER_320x50_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_BANNER);
        put(InAppAdNames.INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_DISPLAY_INTERSTITIAL);
        put(InAppAdNames.VIDEO_INSTREAM_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INSTREAM);
        put(InAppAdNames.VIDEO_OUTSTREAM_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_OUTSTREAM);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED);

        put(InAppAdNames.NATIVE_AD_MAX, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_MAX_NO_BIDS, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);

        put(InAppAdNames.NATIVE_AD_IN_APP, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_FEED_IN_APP, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_LINKS_IN_APP, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);

        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE_GAD, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_ORIGINAL, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED_GAD, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_FEED_GAM, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_UNIFIED_GAD_NO_BIDS, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);
        put(InAppAdNames.NATIVE_AD_GAM_CUSTOM_TEMPLATE_GAD_NO_BIDS, InAppTemplates.RESPONSE_TEMPLATE_NATIVE);

        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_IN_APP_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_GAM_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_ADMOB_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_INTERSTITIAL_320x480_MAX_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_INTERSTITIAL_AD_CONFIGURATION);

        put(InAppAdNames.VIDEO_REWARDED_320x480_IN_APP_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_REWARDED_320x480_GAM_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_REWARDED_320x480_ADMOB_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED_AD_CONFIGURATION);
        put(InAppAdNames.VIDEO_REWARDED_320x480_MAX_WITH_AD_CONFIGURATION, InAppTemplates.RESPONSE_TEMPLATE_VIDEO_REWARDED_AD_CONFIGURATION);
    }};
}
